### PR TITLE
Add animations/demos for Roboto Extemo

### PR DESCRIPTION
**Pull request by RoelN**
A demo page and short instructions explaining the why the CSS is written the way it is (spoiler alert: to work around lack of support or bugs).

### CODE REVIEW

**Comment by RoelN** [comment]
@davelab6 Moved it here, ready for review!

**Comment by davelab6** [comment]
Excellent! @chrissam42 please take a look

**Comment by dberlow** [comment]
Are there basic instructions for me on how to view this?

**Comment by RoelN** [comment]
@dberlow If you open `roboto-animations.html` you'll see the demos:

It'll look like this:

image

**Comment by chrissam42** [comment]
Very nice!

**Pull request merged**
